name: Build Osanka APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up JDK 17 (Обязательно для Android API 34)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libssl-dev libsqlite3-dev libffi-dev uuid-dev imagemagick

      - name: Install pip, setuptools and buildozer
        run: |
          python -m pip install --upgrade pip setuptools virtualenv
          pip install "cython<3.0.0" git+https://github.com

      - name: Check and auto-create icon if missing
        run: |
          if [ ! -f "icon.png" ]; then
            echo "⚠️ Иконка icon.png не найдена! Создаем временную коралловую заглушку..."
            convert -size 512x512 xc:#F28073 icon.png
          fi

      - name: Pre-accept Android Licenses Globally
        run: |
          # Создаем глобальную папку лицензий Android, которую чекают Gradle и sdkmanager
          mkdir -p mkdir -p ~/.android/licenses
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          
          LICENSE_HASHES="
          24333f8a63b6825ea9c5514f83c2829b004d1fee
          893a4cd1c3e7463197415a91248ee225231d5bc0
          d56f5187479451eabf01fb74bf653453a3bc5610
          84831b9409646a918e30573bab4c9c91346d8abd
          4594c0d84d151c0747a4447c283439114e327203
          ed39065b3a4e2862f15c7756ec04ee7a0cb33d1b
          "
          
          # Записываем хэши везде, где их может искать система
          echo "$LICENSE_HASHES" > ~/.android/licenses/android-sdk-license
          echo "$LICENSE_HASHES" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

      - name: Build APK with Buildozer
        run: |
          # 1. Принудительно выставляем Java 17 в переменные окружения для этого шага
          export JAVA_HOME="/usr/lib/jvm/temurin-17-jdk-amd64"
          export PATH="$JAVA_HOME/bin:$PATH"
          
          # 2. Сбрасываем старые переменные путей, чтобы Buildozer качал SDK в свою чистую изолированную папку
          unset ANDROID_SDK_ROOT
          unset ANDROID_HOME
          
          # 3. Запуск сборки в тихом автоматическом режиме
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: osanka-apk
          path: bin/*.apk
